select distinct 
(select CD_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as CD_CNTR,
(select CD_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGCOMP) as CD_PERF_AGCOMP,
(select SG_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGCOMP) as SG_PERF_AGEN_COMP,
(select CD_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGVEND) as CD_PERF_AGVEND,
(select SG_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGVEND) as SG_PERF_AGEN_VEND,
(SELECT CD_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_DEST) AS CD_SMER_DEST,
(SELECT CD_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_ORIG) AS CD_SMER_ORIG,
(select NM_TIPO_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as NM_TIPO_CNTR,
(select NM_SITU_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as NM_SITU_CNTR,
(select TP_MDLD_ENER_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as NM_MDLD_ENER_CNTR,
(select NM_CATG from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGCOMP ) as NM_CATG_COMP,
(select NM_CATG from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGVEND ) as NM_CATG_VEND,
(select cd_agen from dim_agen D where D.id_agen = A.ID_AGVEND) as CD_AGEN_VEND,
(select NM_RZOA_SOCI from dim_agen D where D.id_agen = A.ID_AGVEND) as NM_RZOA_SOCI_VEND,
(select SG_AGEN from dim_agen D where D.id_agen = A.ID_AGVEND) as SG_AGEN_VEND,
(select CD_CNPJ from dim_agen D where D.id_agen = A.ID_AGVEND) as CD_CNPJ_VEND,
(SELECT NM_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_DEST) AS NM_SMER_DEST,
(SELECT NM_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_ORIG) AS NM_SMER_ORIG,
(select cd_agen from dim_agen D where D.id_agen = A.ID_AGCOMP) as CD_AGEN_COMP,
(select NM_RZOA_SOCI from dim_agen D where D.id_agen = A.ID_AGCOMP) as NM_RZOA_SOCI_COMP,
(select SG_AGEN from dim_agen D where D.id_agen = A.ID_AGCOMP) as SG_AGEN_COMP,
(select CD_CNPJ from dim_agen D where D.id_agen = A.ID_AGCOMP) as CD_CNPJ_COMP,
(select cd_evct from dim_evct B where A.id_evct = B.id_evct) as CD_EVCT,
(select mm_ano_evct from dim_evct B where A.id_evct = B.id_evct) AS MM_ANO_REFN,
(select nm_evct from dim_evct B where A.id_evct = B.id_evct) AS NM_EVCT,
null AA_APRC,
null QT_DIF_ARRED,
null QT_DIF_ARRED_CR,
null QT_MNSL_CNTR,
null QT_QEXCED,
null QT_QEXCED_CR,
a.FT_QP_IT,
a.QT_QA,
null FT_SZ_MAX,
null FT_SZ_MIN,
a.QT_PMAX,
null QT_QM,
null QT_AJUSTE_QA,
null FT_F_EFE_CE,
null QT_QM_CE_LIM,
null QT_QM_CED,
null QT_QM_EXC,
null QT_QM_PRE,
a.QT_MMC,
a.QT_MA_CGF,
a.QT_QEC_CER_MED,
a.QT_V_HORAS_FCCEAR,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_INIO ) as DT_H_INI,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_FIM ) as DT_H_FIM,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_INIO ) as DT_H_INI_TZ,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_FIM ) as DT_H_FIM_TZ,
null QT_CEN_SUB_DISP,
null QT_CEN_SUB_QUANT
from FAT_E_CNTR_ANO A
where A.cd_evct =  and A.id_perf_agen in ()
--------------------------------------------------------------------
select distinct 
(select CD_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as CD_CNTR,
(select CD_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGCOMP) as CD_PERF_AGCOMP,
(select SG_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGCOMP) as SG_PERF_AGEN_COMP,
(select CD_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGVEND) as CD_PERF_AGVEND,
(select SG_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGVEND) as SG_PERF_AGEN_VEND,
(SELECT CD_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_DEST) AS CD_SMER_DEST,
(SELECT CD_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_ORIG) AS CD_SMER_ORIG,
(select NM_TIPO_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as NM_TIPO_CNTR,
(select NM_SITU_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as NM_SITU_CNTR,
(select TP_MDLD_ENER_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as NM_MDLD_ENER_CNTR,
(select NM_CATG from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGCOMP ) as NM_CATG_COMP,
(select NM_CATG from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGVEND ) as NM_CATG_VEND,
(select cd_agen from dim_agen D where D.id_agen = A.ID_AGVEND) as CD_AGEN_VEND,
(select NM_RZOA_SOCI from dim_agen D where D.id_agen = A.ID_AGVEND) as NM_RZOA_SOCI_VEND,
(select SG_AGEN from dim_agen D where D.id_agen = A.ID_AGVEND) as SG_AGEN_VEND,
(select CD_CNPJ from dim_agen D where D.id_agen = A.ID_AGVEND) as CD_CNPJ_VEND,
(SELECT NM_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_DEST) AS NM_SMER_DEST,
(SELECT NM_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_ORIG) AS NM_SMER_ORIG,
(select cd_agen from dim_agen D where D.id_agen = A.ID_AGCOMP) as CD_AGEN_COMP,
(select NM_RZOA_SOCI from dim_agen D where D.id_agen = A.ID_AGCOMP) as NM_RZOA_SOCI_COMP,
(select SG_AGEN from dim_agen D where D.id_agen = A.ID_AGCOMP) as SG_AGEN_COMP,
(select CD_CNPJ from dim_agen D where D.id_agen = A.ID_AGCOMP) as CD_CNPJ_COMP,
(select cd_evct from dim_evct B where A.id_evct = B.id_evct) as CD_EVCT,
(select mm_ano_evct from dim_evct B where A.id_evct = B.id_evct) AS MM_ANO_REFN,
(select nm_evct from dim_evct B where A.id_evct = B.id_evct) AS NM_EVCT,
NULL AA_APRC,
A.QT_DIF_ARRED,
NULL QT_DIF_ARRED_CR,
NULL QT_MNSL_CNTR,
NULL QT_QEXCED,
NULL QT_QEXCED_CR,
NULL FT_QP_IT,
NULL QT_QA,
A.FT_SZ_MAX,
A.FT_SZ_MIN,
NULL QT_PMAX,
A.QT_QM,
NULL QT_AJUSTE_QA,
A.FT_F_EFE_CE,
A.QT_QM_CE_LIM,
A.QT_QM_CED,
A.QT_QM_EXC,
A.QT_QM_PRE,
NULL QT_MMC,
NULL QT_MA_CGF,
NULL QT_QEC_CER_MED,
NULL QT_V_HORAS_FCCEAR,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_INIO ) as DT_H_INI,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_FIM ) as DT_H_FIM,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_INIO ) as DT_H_INI_TZ,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_FIM ) as DT_H_FIM_TZ,
A.QT_CEN_SUB_DISP,
A.QT_CEN_SUB_QUANT
from FAT_E_CNTR_MES A
where A.cd_evct =  and A.id_perf_agen in ()
--------------------------------------------------------------------
select distinct 
(select CD_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as CD_CNTR,
(select CD_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGCOMP) as CD_PERF_AGCOMP,
(select SG_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGCOMP) as SG_PERF_AGEN_COMP,
(select CD_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGVEND) as CD_PERF_AGVEND,
(select SG_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGVEND) as SG_PERF_AGEN_VEND,
(SELECT CD_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_DEST) AS CD_SMER_DEST,
(SELECT CD_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_ORIG) AS CD_SMER_ORIG,
(select NM_TIPO_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as NM_TIPO_CNTR,
(select NM_SITU_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as NM_SITU_CNTR,
(select TP_MDLD_ENER_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as NM_MDLD_ENER_CNTR,
(select NM_CATG from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGCOMP ) as NM_CATG_COMP,
(select NM_CATG from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGVEND ) as NM_CATG_VEND,
(select cd_agen from dim_agen D where D.id_agen = A.ID_AGVEND) as CD_AGEN_VEND,
(select NM_RZOA_SOCI from dim_agen D where D.id_agen = A.ID_AGVEND) as NM_RZOA_SOCI_VEND,
(select SG_AGEN from dim_agen D where D.id_agen = A.ID_AGVEND) as SG_AGEN_VEND,
(select CD_CNPJ from dim_agen D where D.id_agen = A.ID_AGVEND) as CD_CNPJ_VEND,
(SELECT NM_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_DEST) AS NM_SMER_DEST,
(SELECT NM_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_ORIG) AS NM_SMER_ORIG,
(select cd_agen from dim_agen D where D.id_agen = A.ID_AGCOMP) as CD_AGEN_COMP,
(select NM_RZOA_SOCI from dim_agen D where D.id_agen = A.ID_AGCOMP) as NM_RZOA_SOCI_COMP,
(select SG_AGEN from dim_agen D where D.id_agen = A.ID_AGCOMP) as SG_AGEN_COMP,
(select CD_CNPJ from dim_agen D where D.id_agen = A.ID_AGCOMP) as CD_CNPJ_COMP,
(select cd_evct from dim_evct B where A.id_evct = B.id_evct) as CD_EVCT,
(select mm_ano_evct from dim_evct B where A.id_evct = B.id_evct) AS MM_ANO_REFN,
(select nm_evct from dim_evct B where A.id_evct = B.id_evct) AS NM_EVCT,
NULL AA_APRC,
NULL QT_DIF_ARRED,
A.QT_DIF_ARRED_CR,
A.QT_MNSL_CNTR,
A.QT_QEXCED,
A.QT_QEXCED_CR,
NULL FT_QP_IT,
NULL QT_QA,
NULL FT_SZ_MAX,
NULL FT_SZ_MIN,
NULL QT_PMAX,
NULL QT_QM,
NULL QT_AJUSTE_QA,
NULL FT_F_EFE_CE,
NULL QT_QM_CE_LIM,
NULL QT_QM_CED,
NULL QT_QM_EXC,
NULL QT_QM_PRE,
NULL QT_MMC,
NULL QT_MA_CGF,
NULL QT_QEC_CER_MED,
NULL QT_V_HORAS_FCCEAR,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_INIO ) as DT_H_INI,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_FIM ) as DT_H_FIM,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_INIO ) as DT_H_INI_TZ,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_FIM ) as DT_H_FIM_TZ,
null QT_CEN_SUB_DISP,
null QT_CEN_SUB_QUANT
from FAT_S_CNTR_MES A
where A.cd_evct =  and A.id_perf_agen in ()
--------------------------------------------------------------------
select distinct 
(select CD_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as CD_CNTR,
(select CD_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGCOMP) as CD_PERF_AGCOMP,
(select SG_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGCOMP) as SG_PERF_AGEN_COMP,
(select CD_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGVEND) as CD_PERF_AGVEND,
(select SG_PERF_AGEN from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGVEND) as SG_PERF_AGEN_VEND,
(SELECT CD_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_DEST) AS CD_SMER_DEST,
(SELECT CD_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_ORIG) AS CD_SMER_ORIG,
(select NM_TIPO_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as NM_TIPO_CNTR,
(select NM_SITU_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as NM_SITU_CNTR,
(select TP_MDLD_ENER_CNTR from dim_CNTR V where V.id_CNTR = A.ID_CNTR) as NM_MDLD_ENER_CNTR,
(select NM_CATG from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGCOMP ) as NM_CATG_COMP,
(select NM_CATG from dim_perf_agen E where E.id_perf_agen = A.ID_PERF_AGVEND ) as NM_CATG_VEND,
(select cd_agen from dim_agen D where D.id_agen = A.ID_AGVEND) as CD_AGEN_VEND,
(select NM_RZOA_SOCI from dim_agen D where D.id_agen = A.ID_AGVEND) as NM_RZOA_SOCI_VEND,
(select SG_AGEN from dim_agen D where D.id_agen = A.ID_AGVEND) as SG_AGEN_VEND,
(select CD_CNPJ from dim_agen D where D.id_agen = A.ID_AGVEND) as CD_CNPJ_VEND,
(SELECT NM_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_DEST) AS NM_SMER_DEST,
(SELECT NM_SMER FROM DIM_SMER Z1 WHERE Z1.ID_SMER = A.ID_SMER_ORIG) AS NM_SMER_ORIG,
(select cd_agen from dim_agen D where D.id_agen = A.ID_AGCOMP) as CD_AGEN_COMP,
(select NM_RZOA_SOCI from dim_agen D where D.id_agen = A.ID_AGCOMP) as NM_RZOA_SOCI_COMP,
(select SG_AGEN from dim_agen D where D.id_agen = A.ID_AGCOMP) as SG_AGEN_COMP,
(select CD_CNPJ from dim_agen D where D.id_agen = A.ID_AGCOMP) as CD_CNPJ_COMP,
(select cd_evct from dim_evct B where A.id_evct = B.id_evct) as CD_EVCT,
(select mm_ano_evct from dim_evct B where A.id_evct = B.id_evct) AS MM_ANO_REFN,
(select nm_evct from dim_evct B where A.id_evct = B.id_evct) AS NM_EVCT,
NULL AA_APRC,
NULL QT_DIF_ARRED,
NULL QT_DIF_ARRED_CR,
NULL QT_MNSL_CNTR,
NULL QT_QEXCED,
NULL QT_QEXCED_CR,
NULL FT_QP_IT,
NULL QT_QA,
NULL FT_SZ_MAX,
NULL FT_SZ_MIN,
NULL QT_PMAX,
NULL QT_QM,
A.QT_AJUSTE_QA,
NULL FT_F_EFE_CE,
NULL QT_QM_CE_LIM,
NULL QT_QM_CED,
NULL QT_QM_EXC,
NULL QT_QM_PRE,
NULL QT_MMC,
NULL QT_MA_CGF,
NULL QT_QEC_CER_MED,
NULL QT_V_HORAS_FCCEAR,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_INIO ) as DT_H_INI,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_FIM ) as DT_H_FIM,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_INIO ) as DT_H_INI_TZ,
(select DT_HR from dim_hr G where G.id_hr = A.ID_HR_FIM ) as DT_H_FIM_TZ,
null QT_CEN_SUB_DISP,
null QT_CEN_SUB_QUANT
from FAT_S_CNTR_ANO A
where A.cd_evct =  and A.id_perf_agen in ()
--------------------------------------------------------------------
